# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protos import grpc_chat_pb2 as protos_dot_grpc__chat__pb2


class MessagingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestConnection = channel.unary_unary(
                '/chat.MessagingService/RequestConnection',
                request_serializer=protos_dot_grpc__chat__pb2.ConnectionMessageRequest.SerializeToString,
                response_deserializer=protos_dot_grpc__chat__pb2.ConnectionStatusReply.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/chat.MessagingService/SendMessage',
                request_serializer=protos_dot_grpc__chat__pb2.Message.SerializeToString,
                response_deserializer=protos_dot_grpc__chat__pb2.Message.FromString,
                )
        self.StreamMessages = channel.unary_stream(
                '/chat.MessagingService/StreamMessages',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_grpc__chat__pb2.Message.FromString,
                )


class MessagingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestConnection(self, request, context):
        """Request connection to the user to chat with
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send a message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Receives a stream of messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessagingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestConnection,
                    request_deserializer=protos_dot_grpc__chat__pb2.ConnectionMessageRequest.FromString,
                    response_serializer=protos_dot_grpc__chat__pb2.ConnectionStatusReply.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=protos_dot_grpc__chat__pb2.Message.FromString,
                    response_serializer=protos_dot_grpc__chat__pb2.Message.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=protos_dot_grpc__chat__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.MessagingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessagingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.MessagingService/RequestConnection',
            protos_dot_grpc__chat__pb2.ConnectionMessageRequest.SerializeToString,
            protos_dot_grpc__chat__pb2.ConnectionStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.MessagingService/SendMessage',
            protos_dot_grpc__chat__pb2.Message.SerializeToString,
            protos_dot_grpc__chat__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat.MessagingService/StreamMessages',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            protos_dot_grpc__chat__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
