# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/grpc_user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/grpc_user.proto\x12\x04\x63hat\"H\n\x1aRegisterUserMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x03\"\'\n\x14RegisterMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x11LookupUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"M\n\x0fLookupUserReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x03\"1\n\x1bRegisterGroupMessageRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\"(\n\x12LookupGroupRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\"6\n\x10LookupGroupReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x12\n\ngroup_name\x18\x02 \x01(\t2\xb2\x02\n\x0bUserService\x12N\n\x0cRegisterUser\x12 .chat.RegisterUserMessageRequest\x1a\x1a.chat.RegisterMessageReply\"\x00\x12>\n\nLookupUser\x12\x17.chat.LookupUserRequest\x1a\x15.chat.LookupUserReply\"\x00\x12P\n\rRegisterGroup\x12!.chat.RegisterGroupMessageRequest\x1a\x1a.chat.RegisterMessageReply\"\x00\x12\x41\n\x0bLookupGroup\x12\x18.chat.LookupGroupRequest\x1a\x16.chat.LookupGroupReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.grpc_user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERUSERMESSAGEREQUEST']._serialized_start=32
  _globals['_REGISTERUSERMESSAGEREQUEST']._serialized_end=104
  _globals['_REGISTERMESSAGEREPLY']._serialized_start=106
  _globals['_REGISTERMESSAGEREPLY']._serialized_end=145
  _globals['_LOOKUPUSERREQUEST']._serialized_start=147
  _globals['_LOOKUPUSERREQUEST']._serialized_end=184
  _globals['_LOOKUPUSERREPLY']._serialized_start=186
  _globals['_LOOKUPUSERREPLY']._serialized_end=263
  _globals['_REGISTERGROUPMESSAGEREQUEST']._serialized_start=265
  _globals['_REGISTERGROUPMESSAGEREQUEST']._serialized_end=314
  _globals['_LOOKUPGROUPREQUEST']._serialized_start=316
  _globals['_LOOKUPGROUPREQUEST']._serialized_end=356
  _globals['_LOOKUPGROUPREPLY']._serialized_start=358
  _globals['_LOOKUPGROUPREPLY']._serialized_end=412
  _globals['_USERSERVICE']._serialized_start=415
  _globals['_USERSERVICE']._serialized_end=721
# @@protoc_insertion_point(module_scope)
