# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/grpc_chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/grpc_chat.proto\x12\x04\x63hat\"V\n\x18\x43onnectionMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x03\"\'\n\x15\x43onnectionStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\"=\n\x07Message\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t2\x9f\x01\n\x10MessagingService\x12\x37\n\x11\x42idirectionalChat\x12\r.chat.Message\x1a\r.chat.Message\"\x00(\x01\x30\x01\x12R\n\x11RequestConnection\x12\x1e.chat.ConnectionMessageRequest\x1a\x1b.chat.ConnectionStatusReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.grpc_chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTIONMESSAGEREQUEST']._serialized_start=32
  _globals['_CONNECTIONMESSAGEREQUEST']._serialized_end=118
  _globals['_CONNECTIONSTATUSREPLY']._serialized_start=120
  _globals['_CONNECTIONSTATUSREPLY']._serialized_end=159
  _globals['_MESSAGE']._serialized_start=161
  _globals['_MESSAGE']._serialized_end=222
  _globals['_MESSAGINGSERVICE']._serialized_start=225
  _globals['_MESSAGINGSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
