# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/grpc_chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/grpc_chat.proto\x12\x04\x63hat\"U\n\x16RegisterMessageRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x03\"\'\n\x14RegisterMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x11LookupUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"M\n\x0fLookupUserReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"Y\n\x12SendMessageRequest\x12\x17\n\x0fsender_username\x18\x01 \x01(\t\x12\x19\n\x11receiver_username\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"3\n\x11SendMessageReplay\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xdb\x01\n\x0b\x43hatService\x12J\n\x0cRegisterUser\x12\x1c.chat.RegisterMessageRequest\x1a\x1a.chat.RegisterMessageReply\"\x00\x12>\n\nLookupUser\x12\x17.chat.LookupUserRequest\x1a\x15.chat.LookupUserReply\"\x00\x12@\n\x0bSendMessage\x12\x18.chat.SendMessageRequest\x1a\x17.chat.SendMessageReplayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.grpc_chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERMESSAGEREQUEST']._serialized_start=32
  _globals['_REGISTERMESSAGEREQUEST']._serialized_end=117
  _globals['_REGISTERMESSAGEREPLY']._serialized_start=119
  _globals['_REGISTERMESSAGEREPLY']._serialized_end=158
  _globals['_LOOKUPUSERREQUEST']._serialized_start=160
  _globals['_LOOKUPUSERREQUEST']._serialized_end=197
  _globals['_LOOKUPUSERREPLY']._serialized_start=199
  _globals['_LOOKUPUSERREPLY']._serialized_end=276
  _globals['_SENDMESSAGEREQUEST']._serialized_start=278
  _globals['_SENDMESSAGEREQUEST']._serialized_end=367
  _globals['_SENDMESSAGEREPLAY']._serialized_start=369
  _globals['_SENDMESSAGEREPLAY']._serialized_end=420
  _globals['_CHATSERVICE']._serialized_start=423
  _globals['_CHATSERVICE']._serialized_end=642
# @@protoc_insertion_point(module_scope)
